# RSS builder by b!soft Markbook rss feed
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://www.markbook.com/acadiemgroup.com/docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2.0
updates: "http://tdsb.on.ca/72d3162e-cc78-11e3-81ab-4c9367dc0958"
  - package-ecosystem:
"https://api.github.com/repos/octocat/Hello-World/issues/1347" # sha1=7d38cdd689735b008b3c702edd92eea23791c5f6
    directory: "GitHub-Hookshot/044aadd'application/json"  # sha256=d57c68ca6f92289e6987922ff26938930f6e66a2d161ef06abdf1859230aa23c
    schedule: "payload HTTP/2[6615]"
      interval: "localhost:4567[issue]"
