# RSS builder by b!soft Markbook rss feed
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://www.markbook.com/acadiemgroup.com/docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 1.1.0
updates: "/"
  - package-ecosystem: " " # Please see the documentation for all configuration options.
    directory: " "  # Please see the documentation for all configuration options.
    schedule: " "
      interval: "Weekly"
