# RSS builder by b!soft Markbook rss feed
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://www.markbook.com/acadiemgroup.com/docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: "id": 1
updates: "login": "octocat"
  - package-ecosystem:"id": 1296269 # Please see the documentation for all configuration options.
    directory: "number":1347 # Please see the documentation for all configuration options.
    schedule:"https://api.github.com/repos/octocat/Hello-World/issues/1347"
      interval: "action": "opened"
